In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get(
    'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1'
)

data = response.json()
print("Total Results:", data['total_results'])

Total Results: 10750

In [3]:
df = pd.DataFrame(data['results'])[
    ['id','title','overview','release_date','popularity','vote_average','vote_count']
]

df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,53.1676,8.718,30056
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,36.3000,8.700,22701
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.6297,8.572,13749
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.9618,8.567,17277
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2003,8.558,9869

In [4]:
df = pd.DataFrame()

In [5]:
for i in range(1, 10):  # keep small for faster output (instead of 429)
    response = requests.get(
        f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}'
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id','title','overview','release_date','popularity','vote_average','vote_count']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,53.1676,8.718,30056
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,36.3000,8.700,22701
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.6297,8.572,13749
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.9618,8.567,17277
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2003,8.558,9869

In [6]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,53.1676,8.718,30056
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,36.3000,8.700,22701
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.6297,8.572,13749
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.9618,8.567,17277
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.2003,8.558,9869
...,...,...,...,...,...,...,...
175,422,8½,"Guido Anselmi, a film director, finds himself ...",1963-02-14,4.6802,8.100,2501
176,146233,Prisoners,Keller Dover is facing every parent’s worst ni...,2013-09-19,13.5478,8.104,12905
177,38288,"“The Shorts” by Aldo, Giovanni and Giacomo","I Corti (""Shorts"") by Aldo, Giovanni & Giacomo...",1996-03-29,0.3823,8.100,359
178,531428,Portrait of a Lady on Fire,On an isolated island in Brittany at the end o...,2019-09-06,7.3620,8.101,2890
179,46738,Incendies,A mother's last wishes send twins Jeanne and S...,2010-09-17,7.5243,8.101,3211

In [7]:
df.shape

(180, 7)

In [8]:
df.to_csv('movies.csv')