In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('1962_2006_walmart_store_openings.csv')
df

,storenum,OPENDATE,date_super,conversion,st,county,STREETADDR,STRCITY,STRSTATE,ZIPCODE,type_store,LAT,LON,MONTH,DAY,YEAR
0,1,7/1/62,3/1/97,1.0,5,7,2110 WEST WALNUT,Rogers,AR,72756,Supercenter,36.342235,-94.07141,7,1,1962
1,2,8/1/64,3/1/96,1.0,5,9,1417 HWY 62/65 N,Harrison,AR,72601,Supercenter,36.236984,-93.09345,8,1,1964
2,4,8/1/65,3/1/02,1.0,5,7,2901 HWY 412 EAST,Siloam Springs,AR,72761,Supercenter,36.179905,-94.50208,8,1,1965
3,8,10/1/67,3/1/93,1.0,5,29,1621 NORTH BUSINESS 9,Morrilton,AR,72110,Supercenter,35.156491,-92.75858,10,1,1967
4,7,10/1/67,NaN,NaN,5,119,3801 CAMP ROBINSON RD.,North Little Rock,AR,72118,Wal-Mart,34.813269,-92.30229,10,1,1967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,5403,1/27/06,1/27/06,0.0,17,19,100 S High Cross Rd,Urbana,IL,61802,Supercenter,40.121648,-88.17649,1,27,2006
2988,3347,1/23/06,1/23/06,0.0,12,105,7450 Cypress Gardens Blvd,Winter Haven,FL,33884,Supercenter,27.997387,-81.68256,1,23,2006
2989,5485,1/27/06,NaN,NaN,17,31,2500 W 95th St,Evergreen Park,IL,60805,Wal-Mart,41.719933,-87.70249,1,27,2006
2990,3425,1/27/06,1/27/06,0.0,48,201,9598 Rowlett Rd,Houston,TX,77034,Supercenter,29.636430,-95.21789,1,27,2006
2991,5193,1/31/06,NaN,NaN,6,65,12721 Moreno Beach Dr,Moreno Valley,CA,92555,Wal-Mart,33.922823,-117.16837,1,31,2006

In [44]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/plotly/datasets/refs/heads/master/311_Animals_short.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Resolution Action Updated Date,Community Board,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Park Facility Name,Park Borough,Latitude,Longitude,Location
0,64345465,3/14/2025 1:20,NaN,NYPD,New York City Police Department,Animal-Abuse,Neglected,Residential Building/House,11207.0,285 COZINE AVENUE,...,3/14/2025 1:59,05 BROOKLYN,BROOKLYN,1017039.0,178484.0,Unspecified,BROOKLYN,40.656513,-73.881825,POINT (-73.88182509318824 40.65651333701598)
1,64349550,3/14/2025 0:44,NaN,NYPD,New York City Police Department,Animal-Abuse,Tortured,Residential Building/House,11412.0,189-04 LIBERTY AVENUE,...,NaN,12 QUEENS,QUEENS,1048718.0,195665.0,Unspecified,QUEENS,40.703497,-73.767487,POINT (-73.76748678190313 40.70349714790391)
2,64342912,3/14/2025 0:25,NaN,NYPD,New York City Police Department,Animal-Abuse,No Shelter,Residential Building,11421.0,87-12 86 STREET,...,3/14/2025 2:46,09 QUEENS,QUEENS,1023620.0,191482.0,Unspecified,QUEENS,40.692163,-73.858031,POINT (-73.85803061095832 40.69216306198625)
3,64344236,3/13/2025 23:33,NaN,NYPD,New York City Police Department,Animal-Abuse,Neglected,Residential Building/House,11237.0,142 WILSON AVENUE,...,NaN,04 BROOKLYN,BROOKLYN,1004894.0,194531.0,Unspecified,BROOKLYN,40.700595,-73.925548,POINT (-73.92554773084896 40.700595346355186)
4,64344359,3/13/2025 21:52,NaN,DSNY,Department of Sanitation,Dead Animal,Cat,Sidewalk,11236.0,9007 FARRAGUT ROAD,...,3/13/2025 23:55,18 BROOKLYN,BROOKLYN,1009484.0,173679.0,Unspecified,BROOKLYN,40.643349,-73.909072,POINT (-73.90907203894598 40.64334941476116)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4964,63587008,1/1/2025 10:07,1/1/2025 10:54,NYPD,New York City Police Department,Animal-Abuse,No Shelter,House and Store,11429.0,225-35 108 AVENUE,...,1/1/2025 10:54,13 QUEENS,QUEENS,1058880.0,197221.0,Unspecified,QUEENS,40.707688,-73.730819,POINT (-73.730819020869 40.70768811036963)
4965,63586660,1/1/2025 10:00,1/2/2025 4:32,DSNY,Department of Sanitation,Dead Animal,Deer,Street,10314.0,621 ROCKLAND AVENUE,...,1/2/2025 4:32,02 STATEN ISLAND,STATEN ISLAND,946282.0,153508.0,Unspecified,STATEN ISLAND,40.587939,-74.136700,POINT (-74.13670004916393 40.587938827826136)
4966,63593076,1/1/2025 9:55,1/2/2025 13:11,DSNY,Department of Sanitation,Dead Animal,Cat,Sidewalk,11226.0,421 EAST 21 STREET,...,1/2/2025 7:09,14 BROOKLYN,BROOKLYN,995686.0,173917.0,Unspecified,BROOKLYN,40.644031,-73.958791,POINT (-73.95879120868675 40.64403123796195)
4967,63589171,1/1/2025 9:33,1/7/2025 10:50,DSNY,Department of Sanitation,Dead Animal,Cat,Street,10469.0,2300 WILLIAMSBRIDGE ROAD,...,1/2/2025 4:02,11 BRONX,BRONX,1023709.0,252541.0,Unspecified,BRONX,40.859753,-73.857351,POINT (-73.85735111920857 40.859753291561546)
4968,63594352,1/1/2025 7:52,1/3/2025 12:08,DSNY,Department of Sanitation,Dead Animal,Bird,Sidewalk,11429.0,113-45 FRANCIS LEWIS BOULEVARD,...,1/2/2025 7:37,13 QUEENS,QUEENS,1053890.0,195151.0,Unspecified,QUEENS,40.702047,-73.748839,POINT (-73.7488386254384 40.702047152003274)

In [45]:
df = pd.read_csv('sample.tsv', sep='\t', skiprows=1, header=None, names=['customer_id','name','age','city','email','total_spent'], usecols=[0, 1, 2, 3, 5, 8])
df

,customer_id,name,age,city,email,total_spent
0,1001,John Smith,28,New York,john.smith@email.com,1500.50
1,1002,Maria Garcia,34,Los Angeles,maria.garcia@email.com,2500.75
2,1003,Li Wei,22,Toronto,li.wei@email.com,800.20
3,1004,Aisha Khan,30,London,aisha.khan@email.com,3200.00
4,1005,Robert Johnson,45,Sydney,robert.j@email.com,5000.00
5,1006,Sofia Martinez,26,Mexico City,sofia.m@email.com,1200.80
6,1007,Ahmed Ali,38,Dubai,ahmed.ali@email.com,1750.60
7,1008,Emma Brown,29,Berlin,emma.brown@email.com,900.00
8,1009,Chen Zhu,31,Beijing,chen.zhu@email.com,1600.40
9,1010,Olivia Davis,27,Tokyo,olivia.d@email.com,1100.90
10,1011,William Wilson,50,Paris,william.w@email.com,7500.00
11,1012,Ava Taylor,23,San Francisco,ava.taylor@email.com,650.00
12,1013,Noah Anderson,36,Mumbai,noah.a@email.com,2200.30
13,1014,Chloe Thomas,32,Amsterdam,chloe.t@email.com,1800.55
14,1015,Liam Wilson,40,Cape Town,liam.w@email.com,3000.80
15,1016,Zara Patel,26,Singapore,zara.patel@email.com,950.00
16,1017,Ethan Lee,29,Seoul,ethan.lee@email.com,1300.00
17,1018,Sophia Clark,24,Madrid,sophia.c@email.com,700.45
18,1019,Aiden Hall,35,Dublin,aiden.h@email.com,2100.70
19,1020,Isabella Scott,30,Wellington,isabella.s@email.com,1600.25

In [46]:
pd.read_csv('1962_2006_walmart_store_openings.csv',index_col='storenum')

,OPENDATE,date_super,conversion,st,county,STREETADDR,STRCITY,STRSTATE,ZIPCODE,type_store,LAT,LON,MONTH,DAY,YEAR
storenum,,,,,,,,,,,,,,,
1,7/1/62,3/1/97,1.0,5,7,2110 WEST WALNUT,Rogers,AR,72756,Supercenter,36.342235,-94.07141,7,1,1962
2,8/1/64,3/1/96,1.0,5,9,1417 HWY 62/65 N,Harrison,AR,72601,Supercenter,36.236984,-93.09345,8,1,1964
4,8/1/65,3/1/02,1.0,5,7,2901 HWY 412 EAST,Siloam Springs,AR,72761,Supercenter,36.179905,-94.50208,8,1,1965
8,10/1/67,3/1/93,1.0,5,29,1621 NORTH BUSINESS 9,Morrilton,AR,72110,Supercenter,35.156491,-92.75858,10,1,1967
7,10/1/67,NaN,NaN,5,119,3801 CAMP ROBINSON RD.,North Little Rock,AR,72118,Wal-Mart,34.813269,-92.30229,10,1,1967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5403,1/27/06,1/27/06,0.0,17,19,100 S High Cross Rd,Urbana,IL,61802,Supercenter,40.121648,-88.17649,1,27,2006
3347,1/23/06,1/23/06,0.0,12,105,7450 Cypress Gardens Blvd,Winter Haven,FL,33884,Supercenter,27.997387,-81.68256,1,23,2006
5485,1/27/06,NaN,NaN,17,31,2500 W 95th St,Evergreen Park,IL,60805,Wal-Mart,41.719933,-87.70249,1,27,2006
3425,1/27/06,1/27/06,0.0,48,201,9598 Rowlett Rd,Houston,TX,77034,Supercenter,29.636430,-95.21789,1,27,2006
5193,1/31/06,NaN,NaN,6,65,12721 Moreno Beach Dr,Moreno Valley,CA,92555,Wal-Mart,33.922823,-117.16837,1,31,2006

In [47]:
pd.read_csv('1962_2006_walmart_store_openings.csv',header=0)

,storenum,OPENDATE,date_super,conversion,st,county,STREETADDR,STRCITY,STRSTATE,ZIPCODE,type_store,LAT,LON,MONTH,DAY,YEAR
0,1,7/1/62,3/1/97,1.0,5,7,2110 WEST WALNUT,Rogers,AR,72756,Supercenter,36.342235,-94.07141,7,1,1962
1,2,8/1/64,3/1/96,1.0,5,9,1417 HWY 62/65 N,Harrison,AR,72601,Supercenter,36.236984,-93.09345,8,1,1964
2,4,8/1/65,3/1/02,1.0,5,7,2901 HWY 412 EAST,Siloam Springs,AR,72761,Supercenter,36.179905,-94.50208,8,1,1965
3,8,10/1/67,3/1/93,1.0,5,29,1621 NORTH BUSINESS 9,Morrilton,AR,72110,Supercenter,35.156491,-92.75858,10,1,1967
4,7,10/1/67,NaN,NaN,5,119,3801 CAMP ROBINSON RD.,North Little Rock,AR,72118,Wal-Mart,34.813269,-92.30229,10,1,1967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,5403,1/27/06,1/27/06,0.0,17,19,100 S High Cross Rd,Urbana,IL,61802,Supercenter,40.121648,-88.17649,1,27,2006
2988,3347,1/23/06,1/23/06,0.0,12,105,7450 Cypress Gardens Blvd,Winter Haven,FL,33884,Supercenter,27.997387,-81.68256,1,23,2006
2989,5485,1/27/06,NaN,NaN,17,31,2500 W 95th St,Evergreen Park,IL,60805,Wal-Mart,41.719933,-87.70249,1,27,2006
2990,3425,1/27/06,1/27/06,0.0,48,201,9598 Rowlett Rd,Houston,TX,77034,Supercenter,29.636430,-95.21789,1,27,2006
2991,5193,1/31/06,NaN,NaN,6,65,12721 Moreno Beach Dr,Moreno Valley,CA,92555,Wal-Mart,33.922823,-117.16837,1,31,2006

In [48]:
pd.read_csv('1962_2006_walmart_store_openings.csv', usecols=['storenum', 'OPENDATE', 'STRCITY'])

      storenum OPENDATE            STRCITY
0            1   7/1/62             Rogers
1            2   8/1/64           Harrison
2            4   8/1/65     Siloam Springs
3            8  10/1/67          Morrilton
4            7  10/1/67  North Little Rock
...        ...      ...                ...
2987      5403  1/27/06             Urbana
2988      3347  1/23/06       Winter Haven
2989      5485  1/27/06     Evergreen Park
2990      3425  1/27/06            Houston
2991      5193  1/31/06      Moreno Valley

[2992 rows x 3 columns]

In [49]:
pd.read_csv('1962_2006_walmart_store_openings.csv', usecols=['STRSTATE']).squeeze()

0       AR
1       AR
2       AR
3       AR
4       AR
        ..
2987    IL
2988    FL
2989    IL
2990    TX
2991    CA
Name: STRSTATE, Length: 2992, dtype: object

In [50]:
pd.read_csv('1962_2006_walmart_store_openings.csv', nrows=100)

,storenum,OPENDATE,date_super,conversion,st,county,STREETADDR,STRCITY,STRSTATE,ZIPCODE,type_store,LAT,LON,MONTH,DAY,YEAR
0,1,7/1/62,3/1/97,1.0,5,7,2110 WEST WALNUT,Rogers,AR,72756,Supercenter,36.342235,-94.07141,7,1,1962
1,2,8/1/64,3/1/96,1.0,5,9,1417 HWY 62/65 N,Harrison,AR,72601,Supercenter,36.236984,-93.09345,8,1,1964
2,4,8/1/65,3/1/02,1.0,5,7,2901 HWY 412 EAST,Siloam Springs,AR,72761,Supercenter,36.179905,-94.50208,8,1,1965
3,8,10/1/67,3/1/93,1.0,5,29,1621 NORTH BUSINESS 9,Morrilton,AR,72110,Supercenter,35.156491,-92.75858,10,1,1967
4,7,10/1/67,NaN,NaN,5,119,3801 CAMP ROBINSON RD.,North Little Rock,AR,72118,Wal-Mart,34.813269,-92.30229,10,1,1967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,102,9/1/74,3/1/95,1.0,5,1,406 E 22ND STREET,Stuttgart,AR,72160,Supercenter,34.479852,-91.53854,9,1,1974
96,129,7/1/75,3/1/94,1.0,40,19,1715 NORTH COMMERCE STREET,Ardmore,OK,73401,Supercenter,34.184742,-97.12655,7,1,1975
97,98,2/1/75,NaN,NaN,22,67,2030 EAST MADISON,Bastrop,LA,71220,Wal-Mart,32.814969,-91.90678,2,1,1975
98,103,8/1/75,8/25/04,1.0,40,125,196 SHAWNEE MALL DRIVE,Shawnee,OK,74804,Supercenter,35.375188,-96.93162,8,1,1975
99,108,2/1/75,NaN,NaN,40,83,1618 SOUTH DIVISION,Guthrie,OK,73044,Wal-Mart,35.857303,-97.43176,2,1,1975

In [51]:
df = pd.read_csv('zomato (1).csv',encoding='latin-1')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [52]:
pd.read_csv('zomato (1).csv', encoding="latin-1",on_bad_lines='skip')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [53]:
df = pd.read_csv('aug_train.csv',dtype={'target':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

In [54]:
df = pd.read_csv('aug_train.csv',dtype={'target':int})
display(df.head())

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [55]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [56]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name
rename("Royal Challengers Bangalore")

'RCB'

In [57]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team2':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,RCB,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [58]:
pd.read_csv('aug_train.csv',na_values=['Male',])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [59]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [60]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)